### ISSUE TITLE
kustomize sample

### ISSUE THREAD

**Issue by pahud** [nwcdlabs/container-mirror#27]
需要提供一個kustomize範例，例如

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 2
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
```

如何透過`kubectl kustomize`生成指向新的image路徑的yaml
